version: '3.8'

services:
  cassandra:
    image: cassandra:3.11
    container_name: kairosdb-test-cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_START_TIMEOUT=120
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - kairosdb-test

  kairosdb-ingest:
    build:
      context: .
      dockerfile: kairosdb-ingest/Dockerfile
    container_name: kairosdb-test-ingest
    environment:
      - KAIROSDB_CASSANDRA_CONTACT_POINTS=cassandra:9042
      - KAIROSDB_CASSANDRA_KEYSPACE=test_kairosdb
      - KAIROSDB_BIND_ADDRESS=0.0.0.0:8080
      - RUST_LOG=debug
    ports:
      - "8080:8080"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - kairosdb-test
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cassandra_data:

networks:
  kairosdb-test:
    driver: bridge