[profile.ci]
default-filter = "all()"
retries = { backoff = "exponential", count = 10, delay = "1s", jitter = true, max-delay = "10s" }
test-threads="num-cpus"
slow-timeout = { period = "60s" }

[profile.ci.junit]
path = "junit.xml"
report-name = "nextest-run"